name: GitHub Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate GitHub Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: YALDAKHOSHPEY
          outputs: |
            dist/github-snake.svg

      - name: Commit and Push SVG
        run: |
          git config user.name "Yalda Snake Bot"
          git config user.email "yaldatwin@users.noreply.github.com"
          git add dist/github-snake.svg
          git commit -m "🐍 Update GitHub activity snake"
          git push
